#################
## APPLICATION ##
#################
server:
  port: 8081
  servlet:
    context-path: /v1/api

spring:
  profiles:
    active: master

integration:
  email:
    host: smtp.gmail.com
    port: 587
    username: ${USER_NAME_SMTP}
    password: ${USER_PASSWORD_SMTP}

internal:
  default:
    email: contato.arrudavictor@gmail.com