#################
## APPLICATION ##
#################
server:
  port: ${PORT_APPLICATION:9001}
  servlet:
    context-path: /v1/api

spring:
  profiles:
    active: master

integration:
  email:
    host: smtp.gmail.com
    port: 587
    username: ${USER_NAME_SMTP:example@gmail.com}
    password: ${USER_PASSWORD_SMTP:example@}

internal:
  default:
    email: ${DEFAULT_EMAIL:contato.arrudavictor@gmail.com}